CREATE TABLE PLAYER
(
    USER_ID CHAR(5) PRIMARY KEY,
    USER_NAME VARCHAR(50) NOT NULL UNIQUE,
    FOREIGN KEY (BAND_ID) REFERENCES BAND(BAND_ID) ON UPDATE CASCADE ON DELETE SET NULL,
    FOREIGN KEY (INTSTRUMENT_NAME) REFERENCES INSTRUMENT(INTSTRUMENT_NAME) ON UPDATE CASCADE ON DELETE RESTRICT, 
    FOREIGN KEY (CITY_NAME) REFERENCES CITY(CITY_NAME) ON UPDATE CASCADE ON DELETE RESTRICT, 
    PLAY_LEVEL VARCHAR(20) NOT NULL,
    AGE INTEGER NOT NULL,
    GENDER VARCHAR(6) NOT NULL,
    PURPOSE VARCHAR(20) NOT NULL
);

CREATE TABLE BAND
(
    BAND_ID CHAR(6) PRIMARY KEY, 
    BAND_NAME VARCHAR(50) NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES PLAYER(USER_ID) ON UPDATE CASCADE ON DELETE SET NULL,
    FOREIGN KEY (GENRE_NAME) REFERENCES GENRE(GENRE_NAME) ON UPDATE CASCADE ON DELETE SET NULL,
    FOREIGN KEY (CITY_NAME) REFERENCES CITY(CITY_NAME) ON UPDATE CASCADE ON DELETE RESTRICT,
    BAND_LEVEL VARCHAR(20) NOT NULL
);

CREATE TABLE CITY
(
    CITY_NAME VARCHAR(30) PRIMARY KEY,
    NUMBER_OF_PLAYERS INTEGER DEFAULT 0,
    NUMBER_OF_BANDS INTEGER DEFAULT 0
);

CREATE TABLE GENRE
(
    GENRE_NAME VARCHAR(40) PRIMARY KEY,
    ORIGIN VARCHAR(30) NOT NULL
);

CREATE TABLE INSTRUMENT
(
    INTSTRUMENT_NAME VARCHAR(40) PRIMARY KEY,
    INSTRUMENT_TYPE VARCHAR(40) NOT NULL,
    INSTRUMENT_ORIGIN VARCHAR(40) NOT NULL
);

CREATE TABLE BAND_REQUEST
(
    REQUEST_ID CHAR(7) PRIMARY KEY,
    FOREIGN KEY (USER_ID) REFERENCES PLAYER(USER_ID) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (INTSTRUMENT_NAME) REFERENCES INSTRUMENT(INTSTRUMENT_NAME) ON UPDATE CASCADE ON DELETE RESTRICT,
    REQUEST_DATE DATE NOT NULL,
    PURPOSE VARCHAR(20) NOT NULL
);

CREATE TABLE MEMBER_REQUEST
(
    REQUEST_ID CHAR(7),
    FOREIGN KEY (BAND_ID) REFERENCES BAND(BAND_ID) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (INTSTRUMENT_NAME) REFERENCES INSTRUMENT(INTSTRUMENT_NAME) ON UPDATE CASCADE ON DELETE RESTRICT,
    REQUEST_DATE DATE NOT NULL,
    GENDER_PREF VARCHAR(6) DEFAULT NULL,
    PURPOSE VARCHAR(20) NOT NULL
);